### ISSUE TITLE
Some attribute issues

### ISSUE THREAD

**Issue by GabrielLin** [gprana/READMEClassifier#3]
Hi, gprana, thanks for your great work. I am using Python 3.6. I am facing following issue when I ran `load_dev_and_eval_datasets.py`

```
Processing ../input/dev_and_eval_readmes/antlinker.go-mqtt.md
Processing ../input/dev_and_eval_readmes/alanwgeorge.Android-CleanArchitecture.md
Abstraction of README file into temporary directory has been completed
Fetching information of section to extract and load
Searching for abstracted heading: #  @abstr_hyperlink
Reading ../temp/abstracted_markdown/xiaobai557.wechat.md
Found the heading for # [Easy WeChat](http://easywechat.org)
Encountered heading in document: ## 特点
'DataFrame' object has no attribute 'set_value'
Traceback (most recent call last):
  File "/home2/xxx/nlp/gprana-readme_classifier/script/helper/extractor.py", line 100, in extract_section_from_abstracted_files
    headings.set_value(i,'content_text_w_o_tags',curr_section_content_w_o_tags)
  File "/home/xxx/.conda/envs/py36ccrm/lib/python3.6/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'set_value'
Loading of section contents has been completed
Finished loading data for 25 pct set
Emptying tables for 75 pct data
Cleanup completed
Processing files from ../input/dataset_2.csv
Traceback (most recent call last):
  File "load_dev_and_eval_datasets.py", line 33, in <module>
    extractor.load_section_overview_from_csv(input_filename_csv, db_filename, f'section_overview_{n}pct')
  File "/home2/xxx/nlp/gprana-readme_classifier/script/helper/extractor.py", line 327, in load_section_overview_from_csv
    if sys.stdout.encoding != 'utf-8':
  File "/home/xxx/.conda/envs/py36ccrm/lib/python3.6/codecs.py", line 408, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BufferedWriter' object has no attribute 'encoding'
```

Could you give me some suggestions? Thanks.

**Comment by gprana** [comment]
Hi,
pandas.DataFrame.set_value() has been removed in newer pandas. Please try replacing it with pandas.DataFrame.at .

**Comment by GabrielLin** [comment]
Thank you. Sorry for the late reply. I miss the notification.

I have fixed the first issues following your instruction. But the second issue still exits:
`AttributeError: '_io.BufferedWriter' object has no attribute 'encoding'`

Which python version do you use?

**Comment by GabrielLin** [comment]
@gprana  Could you help please? Thanks.

**Comment by gprana** [comment]
Hi, I'm using Python 3.7.3

**Comment by GabrielLin** [comment]
> Hi, I'm using Python 3.7.3

I have switched to Python 3.7.3. But the above issue still exists when running `python load_dev_and_eval_datasets.py`
````
Found the heading for # [Easy WeChat](http://easywechat.org)
Encountered heading in document: ## 特点
'DataFrame' object has no attribute 'set_value'
Traceback (most recent call last):
  File "/home4/xxx/gprana-readme_classifier/script/helper/extractor.py", line 100, in extract_section_from_abstracted_files
    headings.set_value(i,'content_text_w_o_tags',curr_section_content_w_o_tags)
  File "/home2/xxx/pkgs/miniconda2/envs/py37ccrm/lib/python3.7/site-packages/pandas/core/generic.py", line 5274, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'set_value'
Loading of section contents has been completed
Finished loading data for 25 pct set
Emptying tables for 75 pct data
Cleanup completed
Processing files from ../input/dataset_2.csv
Traceback (most recent call last):
  File "load_dev_and_eval_datasets.py", line 33, in <module>
    extractor.load_section_overview_from_csv(input_filename_csv, db_filename, f'section_overview_{n}pct')
  File "/home4/xxx/gprana-readme_classifier/script/helper/extractor.py", line 327, in load_section_overview_from_csv
    if sys.stdout.encoding != 'utf-8':
  File "/home2/xxx/pkgs/miniconda2/envs/py37ccrm/lib/python3.7/codecs.py", line 409, in __getattr__
    return getattr(self.stream, name)
AttributeError: '_io.BufferedWriter' object has no attribute 'encoding'

````

**Comment by gprana** [comment]
Hi, I've just updated the code. Please try again.

**Comment by GabrielLin** [comment]
> Hi, I've just updated the code. Please try again.

Thank you very much. The issue has been solved.
