### ISSUE TITLE
About ZeroDivisionError

### ISSUE THREAD

**Issue by jennifer1995** [gprana/READMEClassifier#4]
Hello, when I try to train a model with my own data, it occurs this error
```
Traceback (most recent call last):
  File "classifier_train_model.py", line 83, in <module>
    classifier.fit(features_combined.values, labels_matrix)
  File "../READMEClassifier/script/helper/balancer.py", line 78, in fit
    numDup = totalIns/imbalancedIns - 1
ZeroDivisionError: division by zero
```

So, what may be the problem? Thanks

**Comment by gprana** [comment]
Hi, what's the data composition like? Might want to check for missing label or stray comma on labels
